modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="soundcontrol"
version="${version}"
logoFile="assets/soundcontrol/icon.png"
displayName="${mod_name}"
authors="${mod_authors}"
description="Total control over Minecraft's audio. Mute annoying sounds, adjust individual volumes, mark favorites, and track audio with a built-in radar."
displayURL="https://modrinth.com/mod/sound_control"
issuesURL="https://github.com/lilaktt/soundcontrol/issues"
sourcesURL="https://github.com/lilaktt/soundcontrol"

[[mixins]]
config="soundcontrol.mixins.json"

[[dependencies.soundcontrol]]
    modId="neoforge"
    type="required"
    versionRange="[21.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soundcontrol]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.9,1.21.10)"
    ordering="NONE"
    side="BOTH"
