



plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }  
}

dependencies {
    
    compileOnly 'com.google.code.gson:gson:2.10.1'

    
    compileOnly 'org.slf4j:slf4j-api:2.0.9'

    
    
    compileOnly "net.fabricmc:fabric-loader:0.15.11"
}
